Feature/bitbucket cloud ram 20230802 1
kubiyabot/action-stores pull request #29
Opened 2023-08-07 15:09 UTC by ramibo

2023-08-07 16:25 UTC, asafkubiya requested changes

2023-08-07 16:25 UTC, asafkubiya commented on bitbucket-cloud/bitbucket_client/client.py
> +    #         repository_slug:
I don't like commenting out sections. You can delete it, it exists in git history. Think that this repo should be public. It doesn't look good

2023-08-07 16:36 UTC, ramibo commented on bitbucket-cloud/bitbucket_client/client.py
> +    #         repository_slug:
@asafkubiya 
[Done](https://github.com/kubiyabot/action-stores/commit/eafe23ac2ae9237abc4817d90087016a41497e12)

2023-08-10 12:14 UTC, asafkubiya approved these changes

2023-08-10 12:14 UTC, merged